[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies]
clap = "2.33"
regex = "1.4"
chrono = { version = "0.4", features = ["unstable-locales"] }
